// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ6eUuiIlqNU25lToDTYaHI9TP7NdIV3w',
    appId: '1:3338264763:web:1076bd5a877312274c099e',
    messagingSenderId: '3338264763',
    projectId: 'health-connect-new',
    authDomain: 'health-connect-new.firebaseapp.com',
    storageBucket: 'health-connect-new.appspot.com',
    measurementId: 'G-GKQ5Y1RVRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJHmSdvUmMXmmontza8MXKmYNinOUw7s',
    appId: '1:3338264763:android:bd78381bcb2d71a24c099e',
    messagingSenderId: '3338264763',
    projectId: 'health-connect-new',
    storageBucket: 'health-connect-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkff7m_bxcTonsVr4q7n3YMgNAf2rSpjI',
    appId: '1:3338264763:ios:73dfb954b7fee4c64c099e',
    messagingSenderId: '3338264763',
    projectId: 'health-connect-new',
    storageBucket: 'health-connect-new.appspot.com',
    iosBundleId: 'com.example.healthConnectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkff7m_bxcTonsVr4q7n3YMgNAf2rSpjI',
    appId: '1:3338264763:ios:73dfb954b7fee4c64c099e',
    messagingSenderId: '3338264763',
    projectId: 'health-connect-new',
    storageBucket: 'health-connect-new.appspot.com',
    iosBundleId: 'com.example.healthConnectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ6eUuiIlqNU25lToDTYaHI9TP7NdIV3w',
    appId: '1:3338264763:web:36876a473286031d4c099e',
    messagingSenderId: '3338264763',
    projectId: 'health-connect-new',
    authDomain: 'health-connect-new.firebaseapp.com',
    storageBucket: 'health-connect-new.appspot.com',
    measurementId: 'G-422JDX3LPS',
  );

}